baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Yvonne Geikie | Frontend Developer'

theme = "hugo-resume"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "London, United Kingdom"
email = "y.geikie@gmail.com"
favicon = "/favicon.ico"
firstName = "Yvonne"
lastName = "Geikie"
phone = "+447490199620"
profileImage = "img/profile.jpg"
showQr = true
showContact = false
sections = ["creations", "skills"]
showEducation = false
showExperience = false
showSkills = true
showSocializations = true


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/yvonnegeikie/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/yvonnegeikie/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
